### ISSUE TITLE
Not able to run test in sauce on playwright

### ISSUE THREAD

**Issue by samplehub** [saucelabs/sauce-playwright-runner#178]
TypeError: Cannot read properties of undefined (reading 'browserName')
    at run (D:\sauce-playwright-runner\2.12.0\bundle\src\playwright-runner.js:306:42)

![image](https://user-images.githubusercontent.com/18566869/195627351-1b836733-fb3b-45d3-814c-2e5beb1ff178.png)

**Comment by alexplischke** [comment]
Closing in favor of https://github.com/saucelabs/saucectl/issues/615.
